import { ResumeData, TemplateId } from "./types";

export interface DemoProfileConfig {
  id: TemplateId;
  name: string;
  tag: string;
  desc: string;
  accent: string;
  idealFor: string;
  rating: string;
  candidateRole: string;
  candidateName: string;
  companyHeadline: string;
  data: ResumeData;
}

export const LANDING_DEMO_PROFILES: Record<TemplateId, DemoProfileConfig> = {
  modern: {
    id: "modern",
    name: "Moderne",
    tag: "Recommandé 2026",
    desc: "Mise en page asymétrique dynamique avec barre latérale colorée. Met en avant la polyvalence, les compétences et les réalisations chiffrées.",
    accent: "#2563eb",
    idealFor: "Tech, Marketing, Vente & Gestion de Projets",
    rating: "4.9/5",
    candidateRole: "Responsable Marketing & Croissance Digitale",
    candidateName: "Marc-Aurèle Konan",
    companyHeadline: "Wave Côte d'Ivoire • Abidjan",
    data: {
      id: "demo-resume-modern",
      title: "CV Marc-Aurèle Konan — Lead Growth Marketer",
      updatedAt: new Date().toISOString(),
      targetProfile: "professional",
      language: "fr",
      slug: "cv-demo-modern-marc-aurele",
      isPremium: true,
      personal: {
        firstName: "Marc-Aurèle",
        lastName: "Konan",
        title: "Responsable Marketing & Croissance Digitale",
        email: "m.konan@pro-afrique.com",
        phone: "+225 07 48 12 34 56",
        city: "Abidjan, Cocody",
        country: "Côte d'Ivoire",
        birthDate: "12/08/1993",
        birthPlace: "Abidjan",
        maritalStatus: "Célibataire",
        linkedin: "linkedin.com/in/marc-aurele-konan",
        website: "konan-growth.ci",
        photoUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400",
      },
      summary:
        "Expert en acquisition omnicanale et croissance e-commerce avec 5+ ans d'expérience dans l'écosystème tech ouest-africain. Spécialiste de l'optimisation des funnels de conversion, du marketing de performance et du management d'équipes pluridisciplinaires.",
      experiences: [
        {
          id: "exp-mod-1",
          role: "Lead Growth & Acquisition Marketer",
          company: "Wave Côte d'Ivoire",
          city: "Abidjan",
          country: "Côte d'Ivoire",
          startDate: "Janv 2022",
          endDate: "Présent",
          current: true,
          highlights: [
            "Pilotage de la stratégie d'acquisition utilisateurs B2C/B2B (+42% de volume de transactions annuelles).",
            "Gestion d'un budget marketing de 45 millions FCFA avec une réduction du coût d'acquisition client (CAC) de 28%.",
            "Mise en place de tests A/B multicanaux et reporting en temps réel sous Mixpanel et Google Analytics 4.",
          ],
        },
        {
          id: "exp-mod-2",
          role: "Chef de Projet Digital & Rétention",
          company: "Jumia Côte d'Ivoire",
          city: "Abidjan",
          startDate: "Mars 2020",
          endDate: "Déc 2021",
          current: false,
          highlights: [
            "Coordination des campagnes commerciales nationales (Black Friday, Jumia Anniversary).",
            "Déploiement de workflows d'automatisation WhatsApp et SMS générant +19% de réachat sous 30 jours.",
          ],
        },
      ],
      educations: [
        {
          id: "edu-mod-1",
          degree: "Master en Marketing Digital & Stratégie",
          field: "Commerce Électronique & Data",
          school: "Institut National Polytechnique Félix Houphouët-Boigny (INP-HB)",
          city: "Yamoussoukro",
          year: "2020",
        },
        {
          id: "edu-mod-2",
          degree: "Licence en Gestion Commerciale",
          field: "Action Commerciale & Ventes",
          school: "ESCA / Groupe CSI",
          city: "Abidjan",
          year: "2018",
        },
      ],
      skills: [
        {
          id: "sk-mod-1",
          category: "Acquisition & Stratégie",
          items: ["Growth Hacking", "Google & Meta Ads", "SEO / ASO", "Funnels de Conversion", "Stratégie UEMOA"],
        },
        {
          id: "sk-mod-2",
          category: "Outils & Analyse",
          items: ["Google Analytics 4", "Mixpanel", "HubSpot CRM", "Looker Studio", "Excel Avancé"],
        },
      ],
      languages: [
        { id: "lang-mod-1", name: "Français", level: "Bilingue / Natif" },
        { id: "lang-mod-2", name: "Anglais", level: "Courant" },
      ],
      sections: {
        certifications: [
          { id: "cert-mod-1", title: "Certification Google Ads Search & Video", issuer: "Google Skillshop", year: "2023" },
          { id: "cert-mod-2", title: "HubSpot Inbound Marketing Certified", issuer: "HubSpot Academy", year: "2022" },
        ],
        projects: [],
        interests: [],
        references: [],
        volunteer: [],
      },
      design: {
        template: "modern",
        primaryColor: "#2563eb",
        fontFamily: "sans",
        showPhoto: true,
        spacing: "normal",
      },
    },
  },

  elegant: {
    id: "elegant",
    name: "Élégant",
    tag: "Exécutif & Droit",
    desc: "Typographie raffinée avec empattements, bordures fines et hiérarchie classique. Parfait pour inspirer confiance et rigueur intellectuelle.",
    accent: "#0f172a",
    idealFor: "Droit, Conseil, Enseignement & Postes de Direction",
    rating: "4.9/5",
    candidateRole: "Juriste d'Affaires & Conformité OHADA",
    candidateName: "Aïssata Diop",
    companyHeadline: "Cabinet Panafricain LexAfric • Abidjan",
    data: {
      id: "demo-resume-elegant",
      title: "CV Aïssata Diop — Juriste d'Affaires",
      updatedAt: new Date().toISOString(),
      targetProfile: "professional",
      language: "fr",
      slug: "cv-demo-elegant-aissata-diop",
      isPremium: true,
      personal: {
        firstName: "Aïssata",
        lastName: "Diop",
        title: "Juriste d'Affaires & Conformité OHADA",
        email: "aissata.diop@conseil-lex.ci",
        phone: "+225 05 55 98 76 54",
        city: "Abidjan, Plateau",
        country: "Côte d'Ivoire",
        birthDate: "05/11/1992",
        birthPlace: "Abidjan",
        maritalStatus: "Mariée",
        linkedin: "linkedin.com/in/aissata-diop-ohada",
        website: "aissata-juriste.ci",
        photoUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400",
      },
      summary:
        "Juriste spécialisée en droit des affaires OHADA, gouvernance d'entreprise et réglementation bancaire BCEAO. 6 années d'expérience en cabinet et institution financière dans la sécurisation contractuelle et l'audit de conformité.",
      experiences: [
        {
          id: "exp-ele-1",
          role: "Juriste Senior Contrats & Financements",
          company: "Cabinet Panafricain LexAfric",
          city: "Abidjan",
          country: "Côte d'Ivoire",
          startDate: "Févr 2021",
          endDate: "Présent",
          current: true,
          highlights: [
            "Rédaction et négociation de conventions commerciales, pactes d'actionnaires et garanties bancaires (>3 Milliards FCFA).",
            "Audit de conformité des actes uniformes OHADA et due diligence pour 14 opérations de fusions-acquisitions.",
            "Prévention du risque contentieux et gestion des litiges d'arbitrage auprès de la CCJA.",
          ],
        },
        {
          id: "exp-ele-2",
          role: "Juriste Droit Bancaire & Sûretés",
          company: "Société Générale Côte d'Ivoire",
          city: "Abidjan",
          startDate: "Sept 2018",
          endDate: "Janv 2021",
          current: false,
          highlights: [
            "Instruction juridique des dossiers de crédit et mise en place des garanties hypothécaires et nantissements.",
            "Veille réglementaire et mise en œuvre des directives de la commission bancaire de l'UMOA.",
          ],
        },
      ],
      educations: [
        {
          id: "edu-ele-1",
          degree: "Master 2 Droit Privé Fondamental & Fiscalité",
          field: "Droit des Affaires & Contentieux",
          school: "Université Félix Houphouët-Boigny",
          city: "Abidjan",
          year: "2018",
        },
        {
          id: "edu-ele-2",
          degree: "Certificat de Spécialisation en Arbitrage OHADA",
          field: "Règlement des différends commerciaux",
          school: "ERSUMA (École Régionale Supérieure de la Magistrature)",
          city: "Porto-Novo",
          year: "2019",
        },
      ],
      skills: [
        {
          id: "sk-ele-1",
          category: "Expertise Juridique",
          items: ["Droit des Sociétés OHADA", "Sûretés & Garanties", "Gouvernance & Compliance", "Arbitrage CCJA"],
        },
        {
          id: "sk-ele-2",
          category: "Compétences Techniques",
          items: ["Rédaction Contractuelle", "Due Diligence M&A", "Réglementation BCEAO", "Négociation Stratégique"],
        },
      ],
      languages: [
        { id: "lang-ele-1", name: "Français", level: "Bilingue / Natif" },
        { id: "lang-ele-2", name: "Anglais", level: "Courant" },
      ],
      sections: {
        certifications: [
          { id: "cert-ele-1", title: "Certificat Pratique de Conformité LCB-FT", issuer: "Institut Bancaire UMOA", year: "2021" },
        ],
        projects: [],
        interests: [],
        references: [],
        volunteer: [],
      },
      design: {
        template: "elegant",
        primaryColor: "#0f172a",
        fontFamily: "serif",
        showPhoto: true,
        spacing: "normal",
      },
    },
  },

  corporate: {
    id: "corporate",
    name: "Corporate",
    tag: "Finance & Cadres",
    desc: "Structure institutionnelle carrée avec bandeau supérieur noble. Optimisé pour valoriser l'autorité managériale et les indicateurs chiffrés.",
    accent: "#1e3a8a",
    idealFor: "Finance, Audit, Banque, Assurance & Industrie",
    rating: "4.8/5",
    candidateRole: "Directeur Financier & Contrôleur de Gestion",
    candidateName: "Drissa Bakayoko",
    companyHeadline: "Groupe Agro-Ivoire • PwC Alumni",
    data: {
      id: "demo-resume-corporate",
      title: "CV Drissa Bakayoko — Directeur Financier",
      updatedAt: new Date().toISOString(),
      targetProfile: "professional",
      language: "fr",
      slug: "cv-demo-corporate-drissa-bakayoko",
      isPremium: true,
      personal: {
        firstName: "Drissa",
        lastName: "Bakayoko",
        title: "Directeur Financier & Contrôleur de Gestion",
        email: "d.bakayoko@finance-afrique.com",
        phone: "+225 07 01 23 45 67",
        city: "Abidjan, Marcory",
        country: "Côte d'Ivoire",
        birthDate: "20/03/1988",
        birthPlace: "Bouaké",
        maritalStatus: "Marié",
        linkedin: "linkedin.com/in/drissa-bakayoko-dafv",
        website: "bakayoko-finance.ci",
        photoUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=400",
      },
      summary:
        "Cadre financier supérieur fort de 8 années d'expérience en pilotage budgétaire, consolidation comptable SYSCOHADA et restructuration opérationnelle de filiales multinationales. Expert en modélisation financière et conduite du changement sous ERP SAP.",
      experiences: [
        {
          id: "exp-corp-1",
          role: "Directeur du Contrôle de Gestion & Trésorerie",
          company: "Groupe Industriel Agro-Ivoire",
          city: "Abidjan",
          country: "Côte d'Ivoire",
          startDate: "Sept 2020",
          endDate: "Présent",
          current: true,
          highlights: [
            "Supervision globale du budget opérationnel annuel (15 Milliards FCFA) et des prévisions de cash-flow à 12 mois.",
            "Conduite d'un plan d'optimisation des coûts de transformation industrielle générant une économie récurrente de 14%.",
            "Pilotage de la migration vers SAP S/4HANA Finance réalisée dans les délais et sans rupture de trésorerie.",
          ],
        },
        {
          id: "exp-corp-2",
          role: "Auditeur Financier Senior — Pôle Banques & Assurances",
          company: "PwC Afrique Francophone",
          city: "Abidjan",
          startDate: "Nov 2016",
          endDate: "Août 2020",
          current: false,
          highlights: [
            "Audit légal et certification des comptes de 8 groupes cotés à la BRVM et établissements financiers sous réglementation OHADA.",
            "Coordination et encadrement direct d'équipes de 6 collaborateurs seniors et juniors.",
          ],
        },
      ],
      educations: [
        {
          id: "edu-corp-1",
          degree: "Diplôme Supérieur de Comptabilité & Gestion Financière (DSCGF)",
          field: "Audit, Finance & Contrôle",
          school: "ESCA / Institut National Polytechnique (INP-HB)",
          city: "Yamoussoukro",
          year: "2016",
        },
        {
          id: "edu-corp-2",
          degree: "Licence Professionnelle en Sciences de Gestion",
          field: "Gestion Comptable & Financière",
          school: "Université Félix Houphouët-Boigny",
          city: "Abidjan",
          year: "2013",
        },
      ],
      skills: [
        {
          id: "sk-corp-1",
          category: "Finance & Réglementation",
          items: ["SYSCOHADA Révisé", "Consolidation IFRS", "Modélisation Financière", "Audit Interne", "Trésorerie"],
        },
        {
          id: "sk-corp-2",
          category: "Outils Décisionnels",
          items: ["SAP S/4HANA", "Power BI", "Excel VBA Avancé", "Sage 1000"],
        },
      ],
      languages: [
        { id: "lang-corp-1", name: "Français", level: "Bilingue / Natif" },
        { id: "lang-corp-2", name: "Anglais", level: "Courant" },
      ],
      sections: {
        certifications: [
          { id: "cert-corp-1", title: "Certification Professionnelle Modélisation Financière", issuer: "Corporate Finance Institute", year: "2021" },
        ],
        projects: [],
        interests: [],
        references: [],
        volunteer: [],
      },
      design: {
        template: "corporate",
        primaryColor: "#1e3a8a",
        fontFamily: "sans",
        showPhoto: true,
        spacing: "normal",
      },
    },
  },

  minimal: {
    id: "minimal",
    name: "Minimal",
    tag: "Épuré & Scandinave",
    desc: "Sobriété absolue, typographie sans fard et respiration visuelle maximale. Le choix des candidats qui laissent parler l'impact de leurs résultats.",
    accent: "#18181b",
    idealFor: "Consultants, RH, Communication & Profils Polyvalents",
    rating: "4.8/5",
    candidateRole: "Cheffe de Projet Événementiel & Relations Publiques",
    candidateName: "Stéphanie Gnahoré",
    companyHeadline: "Havas Africa Abidjan • SIFCA Alumni",
    data: {
      id: "demo-resume-minimal",
      title: "CV Stéphanie Gnahoré — Cheffe de Projet RP",
      updatedAt: new Date().toISOString(),
      targetProfile: "professional",
      language: "fr",
      slug: "cv-demo-minimal-stephanie-gnahore",
      isPremium: true,
      personal: {
        firstName: "Stéphanie",
        lastName: "Gnahoré",
        title: "Cheffe de Projet Événementiel & Relations Publiques",
        email: "stephanie.gnahore@event-ci.com",
        phone: "+225 07 77 88 99 00",
        city: "Abidjan, Cocody",
        country: "Côte d'Ivoire",
        birthDate: "14/09/1995",
        birthPlace: "Abidjan",
        maritalStatus: "Célibataire",
        linkedin: "linkedin.com/in/stephanie-gnahore",
        website: "stephanie-rp.com",
        photoUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=400",
      },
      summary:
        "Professionnelle de la communication institutionnelle alliant rigueur logistique et sens du relationnel. Coordination d'envergure de sommets internationaux, gestion de protocoles VIP et couverture médiatique panafricaine.",
      experiences: [
        {
          id: "exp-min-1",
          role: "Cheffe de Projets Événements & Médias Senior",
          company: "Agence Havas Africa Abidjan",
          city: "Abidjan",
          country: "Côte d'Ivoire",
          startDate: "Mars 2022",
          endDate: "Présent",
          current: true,
          highlights: [
            "Direction de production de 18 forums économiques internationaux accueillant plus de 3 000 délégués et ministres.",
            "Négociation et supervision de budgets événementiels cumulés de plus de 280 millions FCFA sans dépassement.",
            "Stratégie de relations presse assurant plus de 130 retombées médias (RTI, Jeune Afrique, RFI, TV5 Monde).",
          ],
        },
        {
          id: "exp-min-2",
          role: "Chargée de Communication Externe",
          company: "Groupe SIFCA",
          city: "Abidjan",
          startDate: "Juil 2019",
          endDate: "Févr 2022",
          current: false,
          highlights: [
            "Organisation des assemblées générales et des réceptions institutionnelles des filiales agro-industrielles.",
            "Rédaction des dossiers de presse et gestion des relations avec les rédactions économiques.",
          ],
        },
      ],
      educations: [
        {
          id: "edu-min-1",
          degree: "Master en Communication des Organisations & RP",
          field: "Stratégie Médias & Protocole",
          school: "ISTC Polytechnique (Institut des Sciences et Techniques de la Communication)",
          city: "Abidjan",
          year: "2019",
        },
        {
          id: "edu-min-2",
          degree: "Licence en Lettres Modernes",
          field: "Expression & Langage",
          school: "Université Félix Houphouët-Boigny",
          city: "Abidjan",
          year: "2017",
        },
      ],
      skills: [
        {
          id: "sk-min-1",
          category: "Communication & RP",
          items: ["Gestion d'Événements Majeurs", "Relations Presse & Médias", "Protocole d'État & VIP", "Gestion de Crise"],
        },
        {
          id: "sk-min-2",
          category: "Outils & Coordination",
          items: ["Gestion Budgétaire", "Asana / Trello", "Canva Pro", "Suite Google Workspace"],
        },
      ],
      languages: [
        { id: "lang-min-1", name: "Français", level: "Bilingue / Natif" },
        { id: "lang-min-2", name: "Anglais", level: "Courant" },
      ],
      sections: {
        certifications: [
          { id: "cert-min-1", title: "Certificat Protocole Diplomatique & Relations Publiques", issuer: "Académie Diplomatique", year: "2021" },
        ],
        projects: [],
        interests: [],
        references: [],
        volunteer: [],
      },
      design: {
        template: "minimal",
        primaryColor: "#18181b",
        fontFamily: "sans",
        showPhoto: true,
        spacing: "normal",
      },
    },
  },

  creative: {
    id: "creative",
    name: "Créatif",
    tag: "Design & Startups",
    desc: "Touches graphiques novatrices, badges stylisés et sections aérées. Conçu pour mettre en avant un portfolio, une sensibilité visuelle et l'innovation.",
    accent: "#7c3aed",
    idealFor: "Designers, Architectes, Médias, Web & Audiovisuel",
    rating: "4.9/5",
    candidateRole: "Lead Product Designer UI/UX & Direction Artistique",
    candidateName: "Yannick Kouadio",
    companyHeadline: "FinTech Djamo • Pulse Studio",
    data: {
      id: "demo-resume-creative",
      title: "CV Yannick Kouadio — Lead UI/UX Designer",
      updatedAt: new Date().toISOString(),
      targetProfile: "professional",
      language: "fr",
      slug: "cv-demo-creative-yannick-kouadio",
      isPremium: true,
      personal: {
        firstName: "Yannick",
        lastName: "Kouadio",
        title: "Lead UI/UX Designer & Direction Artistique",
        email: "yannick@creativestudio.ci",
        phone: "+225 01 40 22 33 44",
        city: "Abidjan, Riviera",
        country: "Côte d'Ivoire",
        birthDate: "18/06/1994",
        birthPlace: "Abidjan",
        maritalStatus: "Célibataire",
        linkedin: "linkedin.com/in/yannick-kouadio-design",
        website: "yannickdesign.ci",
        photoUrl: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=400",
      },
      summary:
        "Lead Designer passionné concevant des expériences numériques intuitives et mémorables pour les leaders de la fintech et du commerce en Afrique de l'Ouest. Spécialiste des applications mobiles à forte adoption et de la direction artistique.",
      experiences: [
        {
          id: "exp-cre-1",
          role: "Lead Product Designer UI/UX",
          company: "FinTech Djamo Côte d'Ivoire",
          city: "Abidjan",
          country: "Côte d'Ivoire",
          startDate: "Juin 2022",
          endDate: "Présent",
          current: true,
          highlights: [
            "Refonte complète de l'expérience d'onboarding mobile : hausse du taux de validation de compte de +34%.",
            "Création et gouvernance d'un Design System unifié pour applications iOS, Android et dashboard web.",
            "Animation de 20+ tests utilisateurs mensuels avec intégration des retours en sprints agiles bi-mensuels.",
          ],
        },
        {
          id: "exp-cre-2",
          role: "Senior UI Designer & Directeur Artistique",
          company: "Studio Digital Pulse",
          city: "Abidjan",
          startDate: "Janv 2020",
          endDate: "Mai 2022",
          current: false,
          highlights: [
            "Conception d'identités visuelles et d'interfaces interactives pour 12 startups africaines en amorçage.",
            "Animation de prototypes haute fidélité sous After Effects et collaboration étroite avec l'équipe front-end.",
          ],
        },
      ],
      educations: [
        {
          id: "edu-cre-1",
          degree: "Bachelor en Design Graphique & Médias Numériques",
          field: "Ergonomie des Interfaces & Direction Artistique",
          school: "Université des Technologies & du Design d'Abidjan",
          city: "Abidjan",
          year: "2020",
        },
        {
          id: "edu-cre-2",
          degree: "Diplôme de Technicien Supérieur (BTS)",
          field: "Arts Graphiques & Sérigraphie",
          school: "Lycée d'Enseignement Artistique (INSAAC)",
          city: "Abidjan",
          year: "2017",
        },
      ],
      skills: [
        {
          id: "sk-cre-1",
          category: "Design Produit & UX",
          items: ["Figma & FigJam", "Design Systems", "Prototypage Interactif", "UX Research", "Wireframing"],
        },
        {
          id: "sk-cre-2",
          category: "Graphisme & Motion",
          items: ["Adobe After Effects", "Photoshop & Illustrator", "Design Mobile First", "Micro-interactions"],
        },
      ],
      languages: [
        { id: "lang-cre-1", name: "Français", level: "Bilingue / Natif" },
        { id: "lang-cre-2", name: "Anglais", level: "Courant" },
      ],
      sections: {
        certifications: [
          { id: "cert-cre-1", title: "Google UX Design Professional Certificate", issuer: "Coursera / Google", year: "2022" },
        ],
        projects: [],
        interests: [],
        references: [],
        volunteer: [],
      },
      design: {
        template: "creative",
        primaryColor: "#7c3aed",
        fontFamily: "sans",
        showPhoto: true,
        spacing: "normal",
      },
    },
  },

  ats: {
    id: "ats",
    name: "ATS Optimisé",
    tag: "Norme Internationale 100%",
    desc: "Format linéaire strict et balises normalisées. Garanti 100% lisible par les robots de recrutement (Workday, Taleo, BambooHR, LinkedIn).",
    accent: "#059669",
    idealFor: "Multinationales, ONG, Emploi à l'International & Ingénierie",
    rating: "5.0/5",
    candidateRole: "Ingénieure Cloud & DevOps Certifiée AWS",
    candidateName: "Fatou Bamba",
    companyHeadline: "Orange Côte d'Ivoire Data Center • MTN Alumni",
    data: {
      id: "demo-resume-ats",
      title: "CV Fatou Bamba — Ingénieure DevOps AWS",
      updatedAt: new Date().toISOString(),
      targetProfile: "professional",
      language: "fr",
      slug: "cv-demo-ats-fatou-bamba",
      isPremium: true,
      personal: {
        firstName: "Fatou",
        lastName: "Bamba",
        title: "Ingénieure Cloud & DevOps Certifiée AWS",
        email: "f.bamba@cloud-infra.ci",
        phone: "+225 07 12 34 56 78",
        city: "Abidjan, Cocody Angré",
        country: "Côte d'Ivoire",
        birthDate: "27/02/1994",
        birthPlace: "Abidjan",
        maritalStatus: "Célibataire",
        linkedin: "linkedin.com/in/fatou-bamba-devops",
        website: "fatou-devops.tech",
        photoUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400",
      },
      summary:
        "Ingénieure Cloud et DevOps certifiée cumulant 5 années d'expertise dans l'automatisation, la conteneurisation et la sécurisation d'infrastructures hautement disponibles pour les opérateurs télécoms et le secteur bancaire.",
      experiences: [
        {
          id: "exp-ats-1",
          role: "Ingénieure Cloud DevOps Senior",
          company: "Orange Côte d'Ivoire — Data Center",
          city: "Abidjan",
          country: "Côte d'Ivoire",
          startDate: "Oct 2021",
          endDate: "Présent",
          current: true,
          highlights: [
            "Migration de 45 applications stratégiques vers des clusters Kubernetes (Amazon EKS) avec 99.99% de disponibilité.",
            "Automatisation intégrale des pipelines CI/CD sous GitLab CI et Terraform, réduisant le temps de release de 4 jours à 20 minutes.",
            "Supervision prédictive de plus de 200 serveurs via Prometheus, Grafana et alerting instantané.",
          ],
        },
        {
          id: "exp-ats-2",
          role: "Administratrice Systèmes & Réseaux",
          company: "MTN Côte d'Ivoire",
          city: "Abidjan",
          startDate: "Août 2018",
          endDate: "Sept 2021",
          current: false,
          highlights: [
            "Maintien en conditions opérationnelles de l'infrastructure serveurs Linux/Windows du siège et des agences régionales.",
            "Déploiement des politiques de sécurité et durcissement des accès conformes aux normes ISO 27001.",
          ],
        },
      ],
      educations: [
        {
          id: "edu-ats-1",
          degree: "Diplôme d'Ingénieur en Télécommunications & Réseaux",
          field: "Systèmes Distribués & Sécurité Réseau",
          school: "ESATIC (École Supérieure Africaine des TIC)",
          city: "Abidjan",
          year: "2018",
        },
        {
          id: "edu-ats-2",
          degree: "Certification AWS Solutions Architect — Associate",
          field: "Architecture Cloud & Sécurité",
          school: "Amazon Web Services Training",
          city: "Abidjan",
          year: "2022",
        },
      ],
      skills: [
        {
          id: "sk-ats-1",
          category: "Cloud, Infrastructure & Conteneurs",
          items: ["Amazon Web Services (AWS)", "Kubernetes (K8s)", "Docker", "Terraform", "Ansible"],
        },
        {
          id: "sk-ats-2",
          category: "CI/CD, Systèmes & Monitoring",
          items: ["GitLab CI / GitHub Actions", "Linux RHEL / Ubuntu", "Python", "Bash", "Prometheus & Grafana"],
        },
      ],
      languages: [
        { id: "lang-ats-1", name: "Français", level: "Bilingue / Natif" },
        { id: "lang-ats-2", name: "Anglais", level: "Courant" },
      ],
      sections: {
        certifications: [
          { id: "cert-ats-1", title: "AWS Certified Solutions Architect — Associate", issuer: "Amazon Web Services", year: "2022" },
          { id: "cert-ats-2", title: "Certified Kubernetes Administrator (CKA)", issuer: "Cloud Native Computing Foundation", year: "2023" },
        ],
        projects: [],
        interests: [],
        references: [],
        volunteer: [],
      },
      design: {
        template: "ats",
        primaryColor: "#059669",
        fontFamily: "sans",
        showPhoto: true,
        spacing: "normal",
      },
    },
  },
};

export function getDemoResumeByTemplate(templateId: TemplateId): DemoProfileConfig {
  return LANDING_DEMO_PROFILES[templateId] || LANDING_DEMO_PROFILES.modern;
}
